apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: torrent-downloader
  name: torrent-downloader
spec:
  replicas: 20
  selector:
    matchLabels:
      io.kompose.service: torrent-downloader
  template:
    metadata:
      labels:
        io.kompose.service: torrent-downloader
    spec:
      containers:
        - image: ghcr.io/apoorva64/torrent-challenge/api:b8d5a1364f821e958fa9cd1ecba244e9111e0f17
          name: torrent-downloader
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: MAGNET
              value: "magnet:?xt=urn:btih:MQPJGACOOI2TXD5IXQDT3D4FK25IYULY&dn=Orangutan%20driving%20golf%20cart%20%5B10%20HOURS%5D.mp4&xl=100983812&tr=http%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce"

      restartPolicy: Always


